// Package signals produces deterministic, filesystem-only facts about a repo:
// detected manifests, languages, and top-level layout. No inference — that is the
// model's job (the ax-signals-inferrer agent authors the inferred signals.md).
package signals

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	fileName = "deterministic-signals.md"
	fpMarker = "<!-- apex-signals-fingerprint: "
	fpSuffix = " -->"
)

// manifest/lock files fingerprinted for staleness and used for language detection.
var manifests = []string{
	"package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
	"go.mod", "go.sum", "Cargo.toml", "Cargo.lock",
	"requirements.txt", "pyproject.toml", "Pipfile", "Pipfile.lock",
	"Gemfile", "Gemfile.lock", "pom.xml", "build.gradle",
}

var langByManifest = map[string]string{
	"package.json":     "JavaScript/TypeScript",
	"go.mod":           "Go",
	"Cargo.toml":       "Rust",
	"requirements.txt": "Python",
	"pyproject.toml":   "Python",
	"Pipfile":          "Python",
	"Gemfile":          "Ruby",
	"pom.xml":          "Java",
	"build.gradle":     "Java",
}

func filePath(root string) string {
	return filepath.Join(root, ".claude", "project", fileName)
}

// fingerprint hashes the present manifests (name+size) and top-level dirs.
func fingerprint(root string) (fp string, present, dirs []string, err error) {
	h := sha256.New()
	for _, m := range manifests {
		fi, statErr := os.Stat(filepath.Join(root, m))
		if statErr == nil && !fi.IsDir() {
			present = append(present, m)
			fmt.Fprintf(h, "%s:%d\n", m, fi.Size())
		}
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return "", nil, nil, err
	}
	for _, e := range entries {
		if e.IsDir() && !strings.HasPrefix(e.Name(), ".") {
			dirs = append(dirs, e.Name())
		}
	}
	sort.Strings(dirs)
	for _, d := range dirs {
		fmt.Fprintf(h, "dir:%s\n", d)
	}
	return hex.EncodeToString(h.Sum(nil)), present, dirs, nil
}

func languages(present []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, m := range present {
		if l, ok := langByManifest[m]; ok && !seen[l] {
			seen[l] = true
			out = append(out, l)
		}
	}
	sort.Strings(out)
	return out
}

// Scan writes deterministic-signals.md and returns its path.
func Scan(root string) (string, error) {
	fp, present, dirs, err := fingerprint(root)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("# Deterministic signals\n\n")
	b.WriteString(fpMarker + fp + fpSuffix + "\n\n")
	b.WriteString("Auto-generated by `apex signals scan`. Filesystem facts only — no inference.\n\n")

	b.WriteString("## Manifests\n")
	if len(present) == 0 {
		b.WriteString("- (none detected)\n")
	}
	for _, m := range present {
		b.WriteString("- " + m + "\n")
	}

	b.WriteString("\n## Languages (by manifest)\n")
	langs := languages(present)
	if len(langs) == 0 {
		b.WriteString("- (unknown)\n")
	}
	for _, l := range langs {
		b.WriteString("- " + l + "\n")
	}

	b.WriteString("\n## Top-level directories\n")
	if len(dirs) == 0 {
		b.WriteString("- (none)\n")
	}
	for _, d := range dirs {
		b.WriteString("- " + d + "/\n")
	}

	p := filePath(root)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(p, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return p, nil
}

// Show returns the signals file contents.
func Show(root string) (string, error) {
	data, err := os.ReadFile(filePath(root))
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// Stale reports freshness: 0 fresh, 1 stale/missing, 2 error.
func Stale(root string) (code int, reason string) {
	data, err := os.ReadFile(filePath(root))
	if os.IsNotExist(err) {
		return 1, "signals file missing — run `apex signals scan`"
	}
	if err != nil {
		return 2, err.Error()
	}
	cur, _, _, err := fingerprint(root)
	if err != nil {
		return 2, err.Error()
	}
	stored := ""
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, fpMarker) {
			stored = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, fpMarker), fpSuffix))
			break
		}
	}
	switch {
	case stored == "":
		return 1, "no fingerprint in signals file — re-scan"
	case stored != cur:
		return 1, "manifests changed since last scan — re-scan"
	}
	return 0, "signals fresh"
}
