// Package followups manages per-entry follow-up records under
// .claude/project/followups/, with a regenerated INDEX.md and a CLOSED.md ledger.
// Two kinds: "finding" (review/cleanup loose ends) and "plan" (deferred work).
package followups

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"apexclaude/internal/fm"
)

func dir(root string) string { return filepath.Join(root, ".claude", "project", "followups") }

// closedFile is the append-only ledger of retired ids. nextID reads it so a
// closed id is never reissued.
const closedFile = "CLOSED.md"

// Entry is one follow-up record.
type Entry struct {
	ID, Title, Kind, Severity, Origin, Status, Created string
}

// nextID returns the next %03d id, taking the high-water mark over BOTH the
// live entry files and the CLOSED.md ledger.
//
// Close removes the entry file, so counting live files alone hands a retired id
// straight back out: close 003 and the next add is also 003, leaving CLOSED.md
// attributing a finished title to a different, open item. Ids are permanent
// once issued — the ledger is what makes them so.
func nextID(d string) string {
	max := 0
	bump := func(n int) {
		if n > max {
			max = n
		}
	}

	entries, _ := os.ReadDir(d)
	for _, e := range entries {
		var n int
		if _, err := fmt.Sscanf(strings.TrimSuffix(e.Name(), ".md"), "%d", &n); err == nil {
			bump(n)
		}
	}

	if data, err := os.ReadFile(filepath.Join(d, closedFile)); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			var n int
			if _, err := fmt.Sscanf(strings.TrimSpace(line), "- %d", &n); err == nil {
				bump(n)
			}
		}
	}

	return fmt.Sprintf("%03d", max+1)
}

// Add writes a follow-up and regenerates the index. Returns the new id.
func Add(root, title, kind, severity, origin, body string, now time.Time) (string, error) {
	d := dir(root)
	if err := os.MkdirAll(d, 0o755); err != nil {
		return "", err
	}
	if kind == "" {
		kind = "finding"
	}
	if severity == "" {
		severity = "nit"
	}
	id := nextID(d)
	meta := map[string]string{
		"id": id, "title": title, "kind": kind, "severity": severity,
		"origin": origin, "status": "open", "created": now.UTC().Format("2006-01-02"),
	}
	doc := fm.Render([]string{"id", "title", "kind", "severity", "origin", "status", "created"}, meta, body)
	if err := os.WriteFile(filepath.Join(d, id+".md"), []byte(doc), 0o644); err != nil {
		return "", err
	}
	return id, Render(root)
}

func entryFiles(d string) []string {
	entries, _ := os.ReadDir(d)
	var out []string
	for _, e := range entries {
		n := e.Name()
		if strings.HasSuffix(n, ".md") && n != "INDEX.md" && n != closedFile {
			out = append(out, n)
		}
	}
	sort.Strings(out)
	return out
}

// List returns every entry file present. Close removes the file it closes, so
// what remains on disk is exactly the open set.
func List(root string) ([]Entry, error) {
	d := dir(root)
	var out []Entry
	for _, name := range entryFiles(d) {
		data, err := os.ReadFile(filepath.Join(d, name))
		if err != nil {
			continue
		}
		m, _ := fm.Parse(string(data))
		out = append(out, Entry{
			ID: m["id"], Title: m["title"], Kind: m["kind"], Severity: m["severity"],
			Origin: m["origin"], Status: m["status"], Created: m["created"],
		})
	}
	return out, nil
}

// Path returns the on-disk path for an entry id.
func Path(root, id string) string { return filepath.Join(dir(root), id+".md") }

// Close appends a one-line ledger entry to CLOSED.md, removes the file, and
// regenerates the index.
func Close(root, id, reason string) error {
	d := dir(root)
	data, err := os.ReadFile(filepath.Join(d, id+".md"))
	if err != nil {
		return err
	}
	m, _ := fm.Parse(string(data))
	if reason == "" {
		reason = "closed"
	}
	line := fmt.Sprintf("- %s — %s (%s)\n", m["id"], m["title"], reason)
	f, err := os.OpenFile(filepath.Join(d, closedFile), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	_, werr := f.WriteString(line)
	cerr := f.Close()
	if werr != nil {
		return werr
	}
	if cerr != nil {
		return cerr
	}
	if err := os.Remove(filepath.Join(d, id+".md")); err != nil {
		return err
	}
	return Render(root)
}

// Render regenerates INDEX.md (plans first, then findings).
func Render(root string) error {
	d := dir(root)
	if err := os.MkdirAll(d, 0o755); err != nil {
		return err
	}
	list, _ := List(root)
	var plans, findings []Entry
	for _, e := range list {
		if e.Kind == "plan" {
			plans = append(plans, e)
		} else {
			findings = append(findings, e)
		}
	}
	var b strings.Builder
	b.WriteString("# Follow-ups index\n\n")
	b.WriteString("Auto-generated by `apex followups render`.\n\n")
	if len(plans) > 0 {
		b.WriteString("## 📋 plans\n")
		for _, e := range plans {
			b.WriteString(fmt.Sprintf("- [%s] %s\n", e.ID, e.Title))
		}
		b.WriteString("\n")
	}
	b.WriteString("## findings\n")
	if len(findings) == 0 {
		b.WriteString("- (none open)\n")
	}
	for _, e := range findings {
		b.WriteString(fmt.Sprintf("- [%s] %s — %s\n", e.ID, e.Severity, e.Title))
	}
	return os.WriteFile(filepath.Join(d, "INDEX.md"), []byte(b.String()), 0o644)
}
