// Package docs catalogs human-facing documentation surfaces and gates on whether
// that set has changed since the last scan. Deterministic only — whether content
// is semantically stale is the model's call (the ax-documentation skill).
package docs

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	fileName = "doc-surfaces.md"
	fpMarker = "<!-- apex-docs-fingerprint: "
	fpSuffix = " -->"
)

func filePath(root string) string {
	return filepath.Join(root, ".claude", "project", fileName)
}

// surfaces returns repo-relative paths of human-facing markdown.
func surfaces(root string) []string {
	var out []string
	for _, n := range []string{"README.md", "CHANGELOG.md"} {
		if fi, err := os.Stat(filepath.Join(root, n)); err == nil && !fi.IsDir() {
			out = append(out, n)
		}
	}
	_ = filepath.WalkDir(filepath.Join(root, "docs"), func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		if strings.HasSuffix(p, ".md") {
			if rel, err := filepath.Rel(root, p); err == nil {
				out = append(out, rel)
			}
		}
		return nil
	})
	sort.Strings(out)
	return out
}

func fingerprint(root string) (string, []string) {
	list := surfaces(root)
	h := sha256.New()
	for _, rel := range list {
		if fi, err := os.Stat(filepath.Join(root, rel)); err == nil {
			fmt.Fprintf(h, "%s:%d\n", rel, fi.Size())
		}
	}
	return hex.EncodeToString(h.Sum(nil)), list
}

// Scan writes the doc-surfaces cache and returns its path.
func Scan(root string) (string, error) {
	fp, list := fingerprint(root)
	var b strings.Builder
	b.WriteString("# Documentation surfaces\n\n")
	b.WriteString(fpMarker + fp + fpSuffix + "\n\n")
	b.WriteString("Auto-generated by `apex docs scan`.\n\n")
	if len(list) == 0 {
		b.WriteString("- (no doc surfaces found)\n")
	}
	for _, s := range list {
		b.WriteString("- " + s + "\n")
	}
	p := filePath(root)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(p, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return p, nil
}

// Stale reports freshness: 0 fresh, 1 stale/missing, 2 error.
func Stale(root string) (int, string) {
	data, err := os.ReadFile(filePath(root))
	if os.IsNotExist(err) {
		return 1, "doc-surfaces cache missing — run `apex docs scan`"
	}
	if err != nil {
		return 2, err.Error()
	}
	cur, _ := fingerprint(root)
	stored := ""
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, fpMarker) {
			stored = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, fpMarker), fpSuffix))
			break
		}
	}
	switch {
	case stored == "":
		return 1, "no fingerprint — re-scan"
	case stored != cur:
		return 1, "doc surfaces changed since last scan — re-scan"
	}
	return 0, "docs fresh"
}
